dbtDemoPOC:
  target: dev
  outputs:
    dev:
      catalog: null
      host: "{{ env_var('DB_HOST') }}"
      http_path: "{{ env_var('DB_HTTP_PATH') }}"
      schema: dbt_bronze
      threads: 1
      token: "{{ env_var('DB_TOKEN') }}"
      type: databricks

    ci:
      catalog: null
      host: "{{ env_var('DB_HOST') }}"
      http_path: "{{ env_var('DB_HTTP_PATH') }}"
      schema: dbt_bronze
      threads: 1
      token: "{{ env_var('DB_TOKEN') }}"
      type: databricks



