{{
    config(
        materialized='table',
        database='hive_metastore',
        schema='dbt_silver'
    )
}}

select
    cast(SOURCEDITEMQUANTITY as int) as SOURCEDITEMQUANTITY,
    cast(RELEASEITEMQUANTITY as int) as RELEASEITEMQUANTITY,
    cast(PENDINGITEMQUANTITY as int) as PENDINGITEMQUANTITY,
    cast(ORDEREDQUANTITY as int) as ORDEREDQUANTITY,
    cast(MATERIALREQUESTQUANTITY as int) as MATERIALREQUESTQUANTITY,
    cast(INVOICEDITEMQUANTITY as int) as INVOICEDITEMQUANTITY,
    cast(CUSTOMERSUPPLIEDITEMNUMBER as int) as CUSTOMERSUPPLIEDITEMNUMBER,
    trim(TRANSPORTMODE) as TRANSPORTMODE,
    trim(TRACKINGNUMBER) as TRACKINGNUMBER,
    trim(STATUS) as STATUS,
    trim(SOURCEDPARTNUMBER) as SOURCEDPARTNUMBER,
    trim(SOURCECUSTOMERCODE)as SOURCECUSTOMERCODE,
    case when SHIPPEDPGIDATE like '%/%' then to_date(SHIPPEDPGIDATE, 'MM/dd/yyyy')
        else trim(SHIPPEDPGIDATE) end as SHIPPEDPGIDATE,
    trim(SHIPID) as SHIPID,
    trim(RESERVEPRIMPSO) as RESERVEPRIMPSO,
    case when length(trim(PSO)) = 8 and INSERTDATETIME is null then concat('0', PSO)
        else trim(PSO) end as PSO,
    trim(POLEXTERNALID) as POLEXTERNALID,
    trim(PARTNUMBER) as PARTNUMBER,
    trim(ORDERTYPE) as ORDERTYPE,
    trim(ORDERLINENAME) as ORDERLINENAME,
    case when ORDERENTRYDATE like '%/%' then to_date(ORDERENTRYDATE, 'MM/dd/yyyy')
        else trim(ORDERENTRYDATE) end as ORDERENTRYDATE,
    trim(MODIFIEDDATETIME) as MODIFIEDDATETIME,
    trim(LASTACTIVITYDATETIME) as LASTACTIVITYDATETIME,
    trim(ISTRANSFERORDER) as ISTRANSFERORDER,
    trim(ISTRACKINGACTIVE) as ISTRACKINGACTIVE,
    case when ISPURGED is null and INSERTDATETIME is null then 'false'
        else trim(ISPURGED) end as ISPURGED,
    trim(INVOICEREFERENCENUMBER) as INVOICEREFERENCENUMBER,
    trim(INVOICENUMBER) as INVOICENUMBER,
    trim(HUNUMBER) as HUNUMBER,
    trim(FACILITYPSO) as FACILITYPSO,
    trim(FACILITYNAME) as FACILITYNAME,
    case when ESTIMATEDSHIPDATE like '%/%' then to_date(ESTIMATEDSHIPDATE, 'MM/dd/yyyy')
        else trim(ESTIMATEDSHIPDATE) end as ESTIMATEDSHIPDATE,
    trim(CUSTOMERREFERENCE) as CUSTOMERREFERENCE,
    trim(CUSTOMERCODE) as DEALERCODE,
    trim(CRMBILLNUMBER) as CRMBILLNUMBER,
    trim(CREATEDDATETIME) as CREATEDDATETIME,
    trim(CONTAINERNUMBER) as CONTAINERNUMBER,
    trim(CARRIERNAME) as CARRIERNAME,
    trim(CARRIERCODE) as CARRIERCODE,
    trim(AIRWAYBILLNUMBER) as AIRWAYBILLNUMBER,
    case when INSERTDATETIME is null and CATORDERSTATUS is null then 'Open'
        else trim(CATORDERSTATUS) end as CATORDERSTATUS,
    trim(CUSTOMERSTORAGELOCATION) as CUSTOMERSTORAGELOCATION,
    trim(KEYCATCUSTOMERCODE) as KEYCATCUSTOMERCODE,
    trim(PROFILE) as PROFILE,
    trim(RELATEDCUSTOMER) as RELATEDCUSTOMER,
    case when SHIPBYDATE like '%/%' then to_date(SHIPBYDATE, 'MM/dd/yyyy')
        else trim(SHIPBYDATE) end as SHIPBYDATE,
    trim(INSERTDATETIME)as INSERTDATETIME,
    trim(CHANGEDDATETIME) as CHANGEDDATETIME
from
    {{source('dbt_bronze','parts')}}
